FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY frontend.py .

# Expose the defaulport
EXPOSE 8501

# Run Streamlit with CORS disabled so it can communicate with your backend
CMD ["streamlit", "run", "frontend.py", "--server.enableCORS", "false"]